# welcome my new project 
**My name is Abdirahman Hussein**

In [83]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [84]:
df = pd.read_csv("raw_car_dataset.csv")
df.head()

    Price  Odometer_km  Doors  Accidents Location  Year
0  $1,500     137830.0    4.0          1     City  1998
1  4171.0          NaN    4.0          0    Rural  2016
2  $5,331     107302.0    4.0          0   Suburb  2014
3  1500.0     141838.0    4.0          1   Suburb  1999
4  1500.0          NaN    3.0          0     City  2022

In [85]:
# initial info
df.isnull().sum()

Price          0
Odometer_km    7
Doors          7
Accidents      0
Location       5
Year           0
dtype: int64

In [86]:
df ['Location'].value_counts()

Location
City      59
Suburb    45
Rural     21
Subrb      8
??         7
Name: count, dtype: int64

In [87]:
df['Location'] = df['Location'].replace({"Subrb": "Suburb", "??" : pd.NA})
df.head(5)

      Price  Odometer_km  Doors  Accidents Location  Year
0    $1,500     137830.0    4.0          1     City  1998
1    4171.0          NaN    4.0          0    Rural  2016
2    $5,331     107302.0    4.0          0   Suburb  2014
3    1500.0     141838.0    4.0          1   Suburb  1999
4    1500.0          NaN    3.0          0     City  2022
5    $1,500     211171.0    4.0          0     <NA>  2003
6    1500.0     222235.0    4.0          2    Rural  2004
7    $1,500     105068.0    5.0          1     City  2002
8    $2,291      90015.0    4.0          0    Rural  2007
9    1500.0     125976.0    2.0          0     City  2002
10   1500.0     127701.0    4.0          0   Suburb  2007
11  10441.0      75947.0    5.0          0    Rural  2019
12   3622.0      82771.0    4.0          1     City  2010
13   2358.0     168796.0    5.0          0    Rural  2022
14   $1,500     218508.0    3.0          0     City  2010
15   1500.0     106410.0    3.0          0     City  2005
16   8638.0      81122.0    4.0          1      NaN  2019
17   4469.0          NaN    4.0          1    Rural  2020
18  16783.0      60292.0    5.0          0     City  2021
19   $6,260          NaN    5.0          0   Suburb  2022
20   1500.0     145347.0    4.0          0     City  1998
21   1500.0     115119.0    4.0          1   Suburb  2011
22   1500.0     194075.0    4.0          0     City  2005
23   1500.0     129053.0    5.0          0    Rural  2004
24   1500.0     148867.0    3.0          2    Rural  2004
25   $7,028     111075.0    4.0          0    Rural  2020
26   $1,500     395000.0    4.0          2      NaN  2019
27   3892.0      46659.0    4.0          1     City  2003
28   1563.0     101785.0    4.0          1   Suburb  2009
29  11480.0          NaN    5.0          0     City  2018
30   1500.0     380000.0    2.0          1   Suburb  2002
31   1500.0     171019.0    3.0          2     City  2015
32   1500.0      89054.0    3.0          0    Rural  2009
33   1500.0     219487.0    4.0          0     City  2023
34   6158.0          NaN    4.0          0     City  2017
35   $2,402      36997.0    2.0          0    Rural  2004
36   3444.0     103128.0    4.0          2     City  2020
37   5423.0     141601.0    4.0          1     City  2019
38   1500.0     105936.0    4.0          0   Suburb  2003
39   $1,500     255931.0    4.0          0   Suburb  2011
40   1500.0     171323.0    4.0          0     City  2019
41   $1,500     223877.0    4.0          3      NaN  2004
42   1500.0     203153.0    4.0          0   Suburb  2004
43   9083.0      18853.0    4.0          0     City  2002
44   1500.0      97334.0    4.0          0   Suburb  1998
45  10464.0       5000.0    3.0          1   Suburb  2011
46   $1,500      81216.0    5.0          2   Suburb  1998
47   1500.0     186906.0    4.0          1     City  2013
48   $5,718      69407.0    5.0          0     City  2009
49   1500.0      81799.0    3.0          0     City  2002

In [88]:
df['Doors'] = df['Doors'].replace({ "" : pd.NA})
df['Odometer_km'] = df['Odometer_km'].replace({"" : pd.NA})
df.head(4)

    Price  Odometer_km  Doors  Accidents Location  Year
0  $1,500     137830.0    4.0          1     City  1998
1  4171.0          NaN    4.0          0    Rural  2016
2  $5,331     107302.0    4.0          0   Suburb  2014
3  1500.0     141838.0    4.0          1   Suburb  1999

In [89]:
print ('clenin price null')
df['Price'] = df['Price'].replace(r"[\?,$]", "" , regex = True).astype('float')
df.head()

clenin price null

    Price  Odometer_km  Doors  Accidents Location  Year
0  1500.0     137830.0    4.0          1     City  1998
1  4171.0          NaN    4.0          0    Rural  2016
2  5331.0     107302.0    4.0          0   Suburb  2014
3  1500.0     141838.0    4.0          1   Suburb  1999
4  1500.0          NaN    3.0          0     City  2022

In [90]:
df['Odometer_km'] = df['Odometer_km'].fillna(df['Odometer_km'].median())
df['Doors'] = df['Doors'].fillna(df['Doors'].mode()[0])
df['Location'] = df['Location'].fillna(df['Location'].mode()[0])
df

      Price  Odometer_km  Doors  Accidents Location  Year
0    1500.0     137830.0    4.0          1     City  1998
1    4171.0     128548.0    4.0          0    Rural  2016
2    5331.0     107302.0    4.0          0   Suburb  2014
3    1500.0     141838.0    4.0          1   Suburb  1999
4    1500.0     128548.0    3.0          0     City  2022
..      ...          ...    ...        ...      ...   ...
140  1500.0     223193.0    3.0          0     City  2003
141  1500.0     124567.0    4.0          2   Suburb  2002
142  1500.0     203153.0    4.0          0   Suburb  2004
143  1500.0     180030.0    4.0          1     City  2009
144  1500.0     211171.0    4.0          0     City  2003

[145 rows x 6 columns]

In [91]:
# removing dublictes
df= df.drop_duplicates()
df.shape

(140, 6)

In [92]:
# cheaking info after cleaning
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 140 entries, 0 to 139
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Price        140 non-null    float64
 1   Odometer_km  140 non-null    float64
 2   Doors        140 non-null    float64
 3   Accidents    140 non-null    int64
 4   Location     140 non-null    object
 5   Year         140 non-null    int64
dtypes: float64(3), int64(2), object(1)
memory usage: 7.7+ KB

In [93]:
df ['Location'].value_counts()

Location
City      68
Suburb    51
Rural     21
Name: count, dtype: int64

In [94]:
# ouliers
def iqr_fun(series, k=1.5):
    q1, q3 = series.quantile([0.25, 0.75])
    iqr = q3 - q1
    lower = q1 - k * iqr
    upper = q3 + k * iqr
    return lower, upper

low_price, high_price = iqr_fun(df['Price'])
low_Odometer_km, high_Odometer_km = iqr_fun(df['Odometer_km'])

df['Price'] = df['Price'].clip(lower=low_price, upper=high_price)
df['Odometer_km'] = df['Odometer_km'].clip(lower=low_Odometer_km, upper=high_Odometer_km)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_28212\3789817598.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price'] = df['Price'].clip(lower=low_price, upper=high_price)
C:\Users\hp\AppData\Local\Temp\ipykernel_28212\3789817598.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Odometer_km'] = df['Odometer_km'].clip(lower=low_Odometer_km, upper=high_Odometer_km)

      Price  Odometer_km  Doors  Accidents Location  Year
0    1500.0     137830.0    4.0          1     City  1998
1    4171.0     128548.0    4.0          0    Rural  2016
2    5331.0     107302.0    4.0          0   Suburb  2014
3    1500.0     141838.0    4.0          1   Suburb  1999
4    1500.0     128548.0    3.0          0     City  2022
..      ...          ...    ...        ...      ...   ...
135  1500.0     170466.0    3.0          1   Suburb  2014
136  1500.0     219401.0    2.0          1     City  2012
137  1500.0     223338.0    4.0          2   Suburb  2023
138  1500.0     168376.0    4.0          0   Suburb  2008
139  1500.0     146382.0    4.0          3    Rural  2009

[140 rows x 6 columns]

In [95]:
# One-Hot Encoding
df = pd.get_dummies(
    df,
    columns=["Location"],
    dtype=int
)

print(df.columns)

Index(['Price', 'Odometer_km', 'Doors', 'Accidents', 'Year', 'Location_City',
       'Location_Rural', 'Location_Suburb'],
      dtype='object')

In [96]:
print(df.head())

    Price  Odometer_km  Doors  Accidents  Year  Location_City  Location_Rural  \
0  1500.0     137830.0    4.0          1  1998              1               0
1  4171.0     128548.0    4.0          0  2016              0               1
2  5331.0     107302.0    4.0          0  2014              0               0
3  1500.0     141838.0    4.0          1  1999              0               0
4  1500.0     128548.0    3.0          0  2022              1               0

   Location_Suburb
0                0
1                0
2                1
3                1
4                0

In [97]:
# Feature Engineering  

CURRENT_YEAR = 2026


df["Car_age"] = CURRENT_YEAR - df["Year"] 

df["Km_per_year"] = df["Odometer_km"] / df["Car_age"]
df["is_Urbun"] = df["Location_City"] + df["Location_Suburb"]

In [98]:
# scaling 

dont_Scale = ["Price"]

numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns.to_list()

exclude_Features = [ c for c in df.columns if c.startswith("Location_")] + ["is_Urbun"] + ["is_Accident"]
num_features_to_scale = [c for c in numeric_cols if c not in dont_Scale and c not in exclude_Features]

scaler = StandardScaler()
df[num_features_to_scale] = scaler.fit_transform( df[num_features_to_scale])

In [116]:
# final info
print("\n=== final info malap ah===")

# print(df.info())
df.head(4)

=== final info malap ah===

,Price,Odometer_km,Doors,Accidents,Year,Location_City,Location_Rural,Location_Suburb,Car_age,Km_per_year,is_Urbun
0,1500.0,0.128390,0.254091,0.316968,-1.686714,1,0,0,1.686714,-0.615631,1
1,4171.0,-0.044709,0.254091,-0.820867,0.794617,0,1,0,-0.794617,0.070446,0
2,5331.0,-0.440923,0.254091,-0.820867,0.518913,0,0,1,-0.518913,-0.267993,1
3,1500.0,0.203135,0.254091,0.316968,-1.548862,0,0,1,1.548862,-0.587024,1

In [123]:
# save data 
df.to_csv("clean_dataset.csv", index=False)